print("K   K W   W")
print("K  K  W   W")
print("K K   W   W")
print("KK    W W W")
print("K K   WW WW")
print("K  K  WW WW")
print("K   K W   W")
// am I joke to you?
print("K   K")
print("K  K ")
print("K K  ")
print("KK   ")
print("K K  ")
print("K  K ")
print("K   K")
print("W   W")
print("W   W")
print("W   W")
print("W W W")
print("WW WW")
print("WW WW")
print("W   W")
